Revert "Test at når funksjonen tar inn 3, returnerer den “Fizz”"
Error: Test failed

This reverts commit b5791aef821a38302ae46a39d6e931a417f7cb48.